name: Deploy VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bash scripts/release-client.sh
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      - run: bash scripts/release-server.sh
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
